[package]
name = "pastaslut"
version = "0.1.0"
authors = ["kirjavascript <xxx@gmail.com>"]
edition = "2018"

[dependencies]
warp = "0.2.2"
bytes = "0.5"
tokio = { version = "0.2", features = ["macros"] }
